/**
 * ZILZAL COIN HUNTER PRO
 * Top-Down Neon Arcade Game
 */
const CoinHunterGame=(()=>{let canvas,ctx,animationId=null,isRunning=false,frame=0,score=0,level=1,combo=0,comboTimer=0,lives=3,coins=[],mines=[],enemies=[],particles=[],powerups=[],keys={};const player={x:250,y:250,radius:15,speed:4,shield:0,magnet:0,boost:0,invincible:0};
function init(el){el.innerHTML=`<div class="coin-hunter"><div class="coin-hunter-header"><span>🪙 <b id="hunter-score">0</b></span><span>🏆 <b id="hunter-best">${window.AuthService?.getHighScore('coin')||0}</b></span><span>❤️ <b id="hunter-lives">3</b></span><span>🔥 Lv.<b id="hunter-level">1</b></span></div><canvas id="coin-hunter-canvas" width="500" height="500"></canvas><button id="hunter-start">🚀 ابدأ الصيد</button><div class="hunter-controls"><button data-key="ArrowUp">⬆️</button><div><button data-key="ArrowLeft">⬅️</button><button data-key="ArrowDown">⬇️</button><button data-key="ArrowRight">➡️</button></div></div><div class="hunter-info">🪙 اجمع العملات — 💣 اهرب من الألغام — 👾 تجنب الأعداء</div></div>`;canvas=document.getElementById('coin-hunter-canvas');ctx=canvas.getContext('2d');document.getElementById('hunter-start').addEventListener('click',start);document.addEventListener('keydown',keyDown);document.addEventListener('keyup',keyUp);document.querySelectorAll('.hunter-controls button').forEach(b=>{let k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true});b.addEventListener('pointerup',()=>keys[k]=false);b.addEventListener('pointerleave',()=>keys[k]=false)});drawWelcome()}
function keyDown(e){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key)){e.preventDefault();keys[e.key]=true}}function keyUp(e){keys[e.key]=false}
function start(){if(animationId)cancelAnimationFrame(animationId);Object.assign(player,{x:canvas.width/2,y:canvas.height/2,speed:4,shield:0,magnet:0,boost:0,invincible:0});frame=score=combo=comboTimer=0;level=1;lives=3;coins=[];mines=[];enemies=[];particles=[];powerups=[];isRunning=true;updateUI();window.SoundEngine?.play('click');loop()}
function pos(){return{x:Math.random()*(canvas.width-60)+30,y:Math.random()*(canvas.height-60)+30}}
function spawnCoin(){let p=pos(),r=Math.random(),type=r>.96?'diamond':r>.84?'gold':'normal';coins.push({...p,radius:type==='diamond'?12:9,type,life:600,angle:0})}
function spawnMine(){let p=pos();mines.push({...p,radius:14,angle:0,pulse:Math.random()*10})}
function spawnEnemy(){let p=pos();enemies.push({...p,radius:15,speed:1.1+level*.08})}
function spawnPowerup(){let p=pos(),types=['shield','magnet','boost'];powerups.push({...p,radius:12,type:types[Math.floor(Math.random()*3)],life:900})}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function updatePlayer(){let s=player.speed;if(player.boost>0){s*=1.8;player.boost--}if(keys.ArrowUp||keys.w||keys.W)player.y-=s;if(keys.ArrowDown||keys.s||keys.S)player.y+=s;if(keys.ArrowLeft||keys.a||keys.A)player.x-=s;if(keys.ArrowRight||keys.d||keys.D)player.x+=s;player.x=Math.max(player.radius,Math.min(canvas.width-player.radius,player.x));player.y=Math.max(player.radius,Math.min(canvas.height-player.radius,player.y));if(player.shield>0)player.shield--;if(player.magnet>0)player.magnet--;if(player.invincible>0)player.invincible--}
function updateCoins(){for(let i=coins.length-1;i>=0;i--){let c=coins[i];c.angle+=.08;c.life--;if(player.magnet>0&&dist(player,c)<150){c.x+=(player.x-c.x)*.08;c.y+=(player.y-c.y)*.08}if(dist(player,c)<player.radius+c.radius){collectCoin(c);coins.splice(i,1)}else if(c.life<=0)coins.splice(i,1)}}
function collectCoin(c){comboTimer=100;combo++;let v=c.type==='diamond'?15:c.type==='gold'?5:1;v*=Math.min(5,1+Math.floor(combo/5));score+=v;particlesAt(c.x,c.y,12);window.SoundEngine?.play('score');updateUI()}
function hit(x,y){if(player.shield>0||player.invincible>0)return;lives--;player.invincible=100;combo=0;comboTimer=0;particlesAt(x,y,30);window.SoundEngine?.play('gameover');updateUI();if(lives<=0)gameOver()}
function updateMines(){for(let m of mines){m.angle+=.05;m.pulse+=.1;if(dist(player,m)<player.radius+m.radius)hit(m.x,m.y)}}
function updateEnemies(){for(let e of enemies){let dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy);if(d){e.x+=dx/d*e.speed;e.y+=dy/d*e.speed}if(dist(player,e)<player.radius+e.radius){hit(e.x,e.y);e.x=Math.random()*canvas.width;e.y=Math.random()*canvas.height}}}
function updatePowerups(){for(let i=powerups.length-1;i>=0;i--){let p=powerups[i];p.life--;if(dist(player,p)<player.radius+p.radius){if(p.type==='shield')player.shield=600;if(p.type==='magnet')player.magnet=700;if(p.type==='boost')player.boost=240;score+=10;window.SoundEngine?.play('score');updateUI();powerups.splice(i,1)}else if(p.life<=0)powerups.splice(i,1)}}
function particlesAt(x,y,n){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=Math.random()*4+1;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:40+Math.random()*30,size:Math.random()*4+2})}}
function updateParticles(){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vx*=.96;p.vy*=.96;p.life--;if(p.life<=0)particles.splice(i,1)}}
function loop(){if(!isRunning)return;frame++;updatePlayer();updateCoins();updateMines();updateEnemies();updatePowerups();updateParticles();let nl=1+Math.floor(score/50);if(nl>level)level=nl;if(comboTimer>0)comboTimer--;else combo=0;if(frame%Math.max(35,75-level*2)===0)spawnCoin();if(frame%Math.max(80,190-level*8)===0)spawnMine();if(frame%Math.max(140,420-level*15)===0)spawnEnemy();if(frame%900===0)spawnPowerup();draw();animationId=requestAnimationFrame(loop)}
function updateUI(){let s=document.getElementById('hunter-score'),l=document.getElementById('hunter-lives'),v=document.getElementById('hunter-level');if(s)s.textContent=score;if(l)l.textContent=lives;if(v)v.textContent=level}
function drawWelcome(){ctx.fillStyle='#050711';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.fillStyle='#ffd166';ctx.font='bold 28px Cairo';ctx.fillText('🪙 COIN HUNTER',250,215);ctx.fillStyle='#00f0ff';ctx.font='17px Cairo';ctx.fillText('اجمع أكبر عدد من العملات',250,255);ctx.fillStyle='#ff0055';ctx.fillText('💣 لا تلمس الألغام!',250,290)}
function draw(){ctx.fillStyle='#050711';ctx.fillRect(0,0,500,500);ctx.strokeStyle='rgba(0,240,255,.07)';for(let x=0;x<500;x+=25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(500,y);ctx.stroke()}drawCoins();drawMines();drawEnemies();drawPowerups();drawParticles();drawPlayer();if(combo>1){ctx.textAlign='center';ctx.font='bold 22px Cairo';ctx.fillStyle='#ff9f1c';ctx.fillText(`🔥 COMBO x${combo}`,250,35)}}
function drawCoins(){coins.forEach(c=>{ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.angle);ctx.shadowBlur=22;ctx.shadowColor=c.type==='diamond'?'#00f0ff':'#ffd166';ctx.fillStyle=c.type==='diamond'?'#00f0ff':c.type==='gold'?'#ff9f1c':'#ffd166';ctx.beginPath();ctx.arc(0,0,c.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#070a10';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.type==='diamond'?'◆':'$',0,1);ctx.restore()})}
function drawMines(){mines.forEach(m=>{ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.angle);ctx.shadowBlur=20;ctx.shadowColor='#ff0055';ctx.fillStyle='#ff0055';ctx.beginPath();ctx.arc(0,0,m.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff0055';ctx.lineWidth=4;for(let i=0;i<8;i++){let a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*10,Math.sin(a)*10);ctx.lineTo(Math.cos(a)*22,Math.sin(a)*22);ctx.stroke()}ctx.restore()})}
function drawEnemies(){enemies.forEach(e=>{ctx.shadowBlur=22;ctx.shadowColor='#9b5de5';ctx.fillStyle='#9b5de5';ctx.beginPath();ctx.arc(e.x,e.y,e.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(e.x-5,e.y-3,3,0,Math.PI*2);ctx.arc(e.x+5,e.y-3,3,0,Math.PI*2);ctx.fill()})}
function drawPowerups(){powerups.forEach(p=>{ctx.shadowBlur=25;ctx.shadowColor='#00ff88';ctx.fillStyle='#00ff88';ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#050711';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.type==='shield'?'🛡':p.type==='magnet'?'🧲':'⚡',p.x,p.y)})}
function drawPlayer(){ctx.save();if(player.invincible>0&&Math.floor(player.invincible/5)%2===0)ctx.globalAlpha=.4;if(player.shield>0){ctx.shadowBlur=30;ctx.shadowColor='#00f0ff';ctx.strokeStyle='#00f0ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x,player.y,25,0,Math.PI*2);ctx.stroke()}ctx.shadowBlur=25;ctx.shadowColor='#00f0ff';ctx.fillStyle='#00f0ff';ctx.beginPath();ctx.arc(player.x,player.y,player.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(player.x,player.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff0055';ctx.beginPath();ctx.moveTo(player.x-10,player.y);ctx.lineTo(player.x-27,player.y-7);ctx.lineTo(player.x-27,player.y+7);ctx.closePath();ctx.fill();ctx.restore()}
function drawParticles(){particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/60);ctx.fillStyle='#ffd166';ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1}
function gameOver(){isRunning=false;if(animationId)cancelAnimationFrame(animationId);let r={earned:score,highscore:score};if(window.AuthService?.saveGameScore)r=window.AuthService.saveGameScore('coin',score);ctx.fillStyle='rgba(0,0,0,.88)';ctx.fillRect(0,0,500,500);ctx.textAlign='center';ctx.fillStyle='#ff0055';ctx.font='bold 30px Cairo';ctx.fillText('💥 انتهت اللعبة',250,185);ctx.fillStyle='#ffd166';ctx.font='20px Cairo';ctx.fillText(`🪙 السكور: ${score}`,250,230);ctx.fillStyle='#00f0ff';ctx.fillText(`🏆 أفضل سكور: ${r.highscore||score}`,250,270);ctx.fillStyle='#fff';ctx.fillText(`🎁 ربحت +${r.earned||0} نقطة`,250,310);ctx.font='14px Cairo';ctx.fillText('اضغط ابدأ للعب مرة أخرى',250,350);let b=document.getElementById('hunter-best');if(b)b.textContent=r.highscore||score}
function destroy(){if(animationId)cancelAnimationFrame(animationId);document.removeEventListener('keydown',keyDown);document.removeEventListener('keyup',keyUp);isRunning=false}
return{init,destroy}})();window.CoinHunterGame=CoinHunterGame;
